title: Rene Garcia on GitHub!
description: Rene Garcia does stuff.
permalink: ':title/'
baseurl: '/flexible-jekyll'
url: ''

# Author Settings
author: Rene Garcia
author-img: rene-garcia.jpg
about-author: >
  I'm, mainly, a back-end software engineer. I write code for fun and as well as professionally. I don't know what will
  wind on this site in the long run yet, but I hope it'll be interesting.
social-github: renegarciadieguez

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
